### ISSUE TITLE
Missing models

### ISSUE THREAD

**Issue by anthonyrathe** [mikacuy/point2cyl#2]
Hi,

First of all many thanks for your incredibly exciting research and for publishing your code!
I recently tried to run your `train_Point2Cyl` script, however this seems to assume a `models` folder to be present in the root directory, containing model files (such as `pointnet_extrusion`). Unfortunately this folder is not yet part of the repository. Are you planning on publishing these models and if so, what would be the timeline?

Many thanks in advance for your reply!

Best regards,
Anthony

**Comment by mikacuy** [comment]
Hi Anthony,

Just updated the repo, can you try again and let us know if it works okay? 

Thanks,
Mika

**Comment by anthonyrathe** [comment]
Hi Mika,

Thanks for updating your repo! All seems to work now :)

Thanks again,
Anthony
