### ISSUE TITLE
Got some bad results

### ISSUE THREAD

**Issue by MasterOrigamii** [mikacuy/point2cyl#3]
After I trained with your code, I got some bad results when testing. Specifically, there is a clear difference between the output mesh and the input point cloud. May I ask if this is normal? Or do you have any ideas to help me improve this result?
Thank you!

![image](https://user-images.githubusercontent.com/50735355/199198897-eed9ade2-e67f-4377-8ae5-df351872a866.png)

The two pictures above are a set of data I tested, the input point cloud on the left and the output mesh on the right. The shape's file name is 41859_173a686e_0008_2.
Hope this helps you understand my problem.

**Comment by mikacuy** [comment]
Hi,

You can try to play around with these flags in the visualizer:

### For post processing
parser.add_argument('--seg_post_process', action='store_true')
parser.add_argument('--scale_post_process', action='store_true')
parser.add_argument('--extent_post_process', action='store_true')
parser.add_argument('--igr_post_process', action='store_true')
parser.add_argument('--igr_post_process_reinit', action='store_true')

I think the problem in your output is the sketch implicit has to be refitted. Or the base/barrel segmentation might also be off.

Best,
Mika

**Comment by MasterOrigamii** [comment]
Thanks for your prompt reply! I'll look into it.

**Comment by MasterOrigamii** [comment]
Dear Mika,

I sent you a request email privately a few days ago, did you receive it?

Best,
MO

**Comment by mikacuy** [comment]
Just responded.

**Comment by MasterOrigamii** [comment]
Thanks for your help, I'm closing this issue.
