### ISSUE TITLE
Pretrained weights on DeepCAD dataset

### ISSUE THREAD

**Issue by SadilKhan** [mikacuy/point2cyl#4]
Hello,
Can you please share the pretrained weights on DeepCAD dataset?

Thank you.
Regards,
Mohammad Sadil khan

**Comment by mikacuy** [comment]
Hi Mohammad,

Apologies for the slight delay in the response. Here is the pretrained DeepCAD model. It was also just uploaded to the git repo.
[Point2Cyl_DeepCAD.zip](https://github.com/mikacuy/point2cyl/files/10702532/Point2Cyl_DeepCAD.zip)


Best,
Mika

**Comment by SadilKhan** [comment]
Hello,
Thank you.

Regards,
Mohammad
